### ISSUE TITLE
Navbar doesn't allow empty "projectUrl" parameter as in example

### ISSUE THREAD

**Issue by rachelmarconi** [UrbanInstitute/dataviz-components#70]
# Problem
The [first Storybook example](https://urbaninstitute.github.io/dataviz-components/?path=/docs/components-navbar--docs) shows a blank Navbar with just the Urban logo as being defined as `<Navbar />`, but in practice, if you don't want to put a heading in the navbar, the component still asks for `projectUrl` to be defined, unlike in the example. There is no default set for the parameter, even if it doesn't have any title text to target. 

`Property 'projectUrl' is missing in type '{}' but required in type '{ projectUrl: string; title?: string | undefined; brand?: "urban" | "tpc" | undefined; sticky?: boolean | undefined; }'`

# Solution
There should be a default assigned to `projectUrl` as `www.urban.org` for those cases where no title is needed, or we need to update the example in Storybook to reflect that a `projectUrl` is needed for a default state.

**Comment by mitchthorson** [comment]
Good catch! The other solution would be to update the component to make the `projectUrl` actually optional and make the <a> tag conditional in the navbar as well as the title, giving the most flexibility to provide
- `title` (optional)
- `projectUrl` (optional)

That way we could have a `<Navbar>` with no title at all, `<Navbar>` with a title and no link, OR `<Navbar>` with a title that links. I am in favor of more options vs defaulting to something that is unlikely the desired outcome (project title linking to the Urban home page).

**Comment by rachelmarconi** [comment]
Def agreed it's best to set both `title` and `projectUrl` to optional and letting devs sandbox for the outcome we want-- so that's setting `projectUrl` to default to `""` and then setting another conditional render option in `Navbar.svelte` to check if there's `title` but no `projectUrl` and render title with no link -- and also adding that as a story in `Navbar.stories.svelte`. On it 👍
