### ISSUE TITLE
Type error for urbanColors.blue (and the like)

### ISSUE THREAD

**Issue by benkates** [UrbanInstitute/dataviz-components#73]
`Property 'blue' does not exist on type 'typeof _default'.` looks like only the functions (`getBlues()`) are only explicitly exported...

**Comment by mitchthorson** [comment]
Looks like when Svelte generates the types it doesn't like this syntax: https://github.com/UrbanInstitute/dataviz-components/blob/main/src/lib/utils/urbanColors.js#L262

If you try to use it, `urbanColors.blue` does in fact exist, but typescript can't tell. I can update the way it is exported to avoid the type error, but if you're using this in the meantime I think you can ignore it and it will still work.
